play_song:
  target:
    entity:
      integration: pianodisc_prodigy
      domain: media_player
  fields:
    song:
      required: true
      example: "Clair de Lune"
      selector:
        text:
    volume:
      required: false
      example: 55
      selector:
        number:
          min: 0
          max: 100
          mode: slider
    restore_volume_after:
      required: false
      default: false
      selector:
        boolean:

create_playlist:
  target:
    entity:
      integration: pianodisc_prodigy
      domain: media_player
  fields:
    name:
      required: true
      example: "Dinner Service"
      selector:
        text:
    songs:
      required: false
      example:
        - "Clair de Lune"
      selector:
        object:
    excludes:
      required: false
      example:
        - "/sd/Demo Song.mid"
      selector:
        object:
    sort:
      required: false
      default: "Shuffle"
      selector:
        select:
          options:
            - "Shuffle"
            - "Cycle"
          custom_value: true
    repeat:
      required: false
      default: 1
      selector:
        number:
          min: 0
          max: 99
          mode: box

update_playlist:
  target:
    entity:
      integration: pianodisc_prodigy
      domain: media_player
  fields:
    playlist:
      required: true
      example: "Dinner Service"
      selector:
        text:
    name:
      required: false
      example: "Evening Service"
      selector:
        text:
    sort:
      required: false
      selector:
        select:
          options:
            - "Shuffle"
            - "Cycle"
          custom_value: true
    repeat:
      required: false
      selector:
        number:
          min: 0
          max: 99
          mode: box

delete_playlist:
  target:
    entity:
      integration: pianodisc_prodigy
      domain: media_player
  fields:
    playlist:
      required: true
      example: "Dinner Service"
      selector:
        text:

add_playlist_song:
  target:
    entity:
      integration: pianodisc_prodigy
      domain: media_player
  fields:
    playlist:
      required: true
      example: "Dinner Service"
      selector:
        text:
    song:
      required: true
      example: "Clair de Lune"
      selector:
        text:
    exclude:
      required: false
      default: false
      selector:
        boolean:

remove_playlist_song:
  target:
    entity:
      integration: pianodisc_prodigy
      domain: media_player
  fields:
    playlist:
      required: true
      example: "Dinner Service"
      selector:
        text:
    song:
      required: true
      example: "Clair de Lune"
      selector:
        text:
    exclude:
      required: false
      default: false
      selector:
        boolean:
